services:
  app:
    image: deathzzz/devops-for-programmers-project-74
    build:
      context: .
      dockerfile: Dockerfile
    command: npm run dev
    ports:
      - 8080:8080
    volumes:
      - "./app:/app"
   
  caddy:
    image: caddy:2
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./services/caddy/Caddyfile:/etc/caddy/Caddyfile